config/routes.rb
Rails.application.routes.draw do
  resources :pruebas

   root 'pruebas#index'

end

app/models/prueba.rb
class Prueba < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pruebas_controller.rb
class PruebasController < ApplicationController
  before_action :set_prueba, only: [:show, :edit, :update, :destroy]

  # GET /pruebas
  # GET /pruebas.json
  def index
    @pruebas = Prueba.all
  end

  # GET /pruebas/1
  # GET /pruebas/1.json
  def show
  end

  # GET /pruebas/new
  def new
    @prueba = Prueba.new
  end

  # GET /pruebas/1/edit
  def edit
  end

  # POST /pruebas
  # POST /pruebas.json
  def create
    @prueba = Prueba.new(prueba_params)

    respond_to do |format|
      if @prueba.save
        format.html { redirect_to @prueba, notice: 'Prueba was successfully created.' }
        format.json { render :show, status: :created, location: @prueba }
      else
        format.html { render :new }
        format.json { render json: @prueba.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pruebas/1
  # PATCH/PUT /pruebas/1.json
  def update
    respond_to do |format|
      if @prueba.update(prueba_params)
        format.html { redirect_to @prueba, notice: 'Prueba was successfully updated.' }
        format.json { render :show, status: :ok, location: @prueba }
      else
        format.html { render :edit }
        format.json { render json: @prueba.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pruebas/1
  # DELETE /pruebas/1.json
  def destroy
    @prueba.destroy
    respond_to do |format|
      format.html { redirect_to pruebas_url, notice: 'Prueba was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prueba
      @prueba = Prueba.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prueba_params
      params[:prueba]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pruebas_helper.rb
module PruebasHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Party Cat', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Prueba1" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Prueba1" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pruebas/_comentarios.html.erb
<h2>Comentarios blablablubli</h2>

app/views/pruebas/_form.html.erb
<%= form_for(@prueba) do |f| %>
  <% if @prueba.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prueba.errors.count, "error") %> prohibited this prueba from being saved:</h2>

      <ul>
      <% @prueba.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<form>
  <div class="row">
    <div class="large-12 columns">
        <input type="text" placeholder="Nombre" />
    </div>
  </div>
  <div class="row">
    <div class="large-4 columns">
        <input type="text" placeholder="Email" />
    </div>
    <div class="large-4 columns">
        <input type="text" placeholder="Teléfono" />
    </div>
    <div class="large-4 columns">
        <input type="text" placeholder="Rut" />
    </div>
    <div class="large-4 columns">
        <input type="text" placeholder="Contraseña" />
    </div>
      <div class="large-4 columns">
        <input type="text" placeholder="Confirma tu contraseña" />
    </div>
    </div>
  </div>

  <div class="row">
    <div class="large-12 columns">
      <label>Elige tu horario de atención
        <select>
          <option value="husker">No</option>
          <option value="starbuck">Bueno ya</option>
          <option value="hotdog">Ni idea</option>
        </select>
      </label>
    </div>
  </div>
  <div class="row">
    <div class="large-6 columns">
      <input type="radio" name="pokemon" value="Red" id="pokemonRed"><label for="pokemonRed">Abierto las 24 horas</label>
    </div>
</form>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pruebas/_informacion.html.erb
<div id="imageninformacion">

      <img src="http://hibult-static.websplanetdemo.com/var/m_3/3f/3f6/3576/53687-alo-liquidos-botillerias-a-domicilio-fachada-de-local.jpg" alt="" />
      
<!--       <h2>Líquidos</h2> -->
</div>

<h4>Dirección:</h4>
<p>Tobalaba 911, Providencia, Santiago</p>

<h4>Horario de atención</h4>
<p>12:00 pm - 03:00 am</p>

<h4>Teléfono</h4>
<p>(02) 21234567</p>

<h4>Sitio Web</h4>
<p>Liquidos.cl</p>

<h4>Medios de pago</h4>
<p></p>

app/views/pruebas/_promosyproductos.html.erb
<h2>Promos y productos</h2>

app/views/pruebas/edit.html.erb
<h1>Editing Prueba</h1>

<%= render 'form' %>

<%= link_to 'Show', @prueba %> |
<%= link_to 'Back', pruebas_path %>

app/views/pruebas/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="show-for-large-up">This text is shown on large screens and up.</strong>">Hola</h1>

  <tbody>
    <% @pruebas.each do |prueba| %>
      <tr>
        <td><%= link_to 'Show', prueba %></td>
        <td><%= link_to 'Edit', edit_prueba_path(prueba) %></td>
        <td><%= link_to 'Destroy', prueba, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<a href="#" class="button show-for-large-up">Miau</a>

<div class="tabs-content">
  <div class="content active" id="panel1">
    <%= render 'promosyproductos' %>
  </div>
  <div class="content" id="panel2">
    <%= render 'informacion' %>
  </div>
  <div class="content" id="panel3">
    <%= render 'comentarios' %>
  </div>
</div>

<ul class="tabs show-for-small-only" data-tab>
  <li class="tab-title active"><a href="#panel1">Promos y productos</a></li>
  <li class="tab-title"><a href="#panel2">Información</a></li>
  <li class="tab-title"><a href="#panel3">Comentarios</a></li>
</ul>

app/views/pruebas/new.html.erb
<h1>Paso 1: Rellena con tus datos personales</h1>

<%= render 'form' %>

<%= link_to 'Back', pruebas_path %>

app/views/pruebas/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_prueba_path(@prueba) %> |
<%= link_to 'Back', pruebas_path %>